name: connectivity_widget
description: A widget that shows the user if the phone is connected to the internet or not
version: 0.1.8
homepage: https://github.com/Vanethos/flutter_connectivity_widget/
issue_tracker: https://github.com/Vanethos/flutter_connectivity_widget/issues

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart:
  simple_connectivity: 
  stream_disposable: 
  http: 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
